### ISSUE TITLE
F_OSC is undefined identifier

### ISSUE THREAD

**Issue by spellbinder103** [pranjal-joshi/Arduino-for-8051#1]
when compiler with Keil C51, get error in arduino51.h

Line 206: error C202: 'F_OSC': undefined identifier
Line 232: error C202: 'F_OSC': undefined identifier
Line 234: error C202: 'F_OSC': undefined identifier

**Comment by spellbinder103** [comment]
> when compiler with Keil C51, get error in arduino51.h
> 
> Line 206: error C202: 'F_OSC': undefined identifier
> Line 232: error C202: 'F_OSC': undefined identifier
> Line 234: error C202: 'F_OSC': undefined identifier

my fault, i just forget to unremarked at top of document.

**Comment by pranjal-joshi** [comment]
You must define the F_OSC value in your program according to your crystal frequency.
